// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://navbvwimzfakdzwwzajk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hdmJ2d2ltemZha2R6d3d6YWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjcyMjg2NDksImV4cCI6MjA0MjgwNDY0OX0.aSqNet2HS9vC8Znd1VTi3m8J4PUikorSY-JnhF2_gp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);